/*******************************************************************************
 DO NOT EDIT
 This file was automatically generated by the Impulse C Compiler.

 Copyright (c) 2002-2009 by Impulse Accelerated Technologies, Inc.
 All rights reserved.

 This source file may be used and redistributed without charge
 subject to the provisions of the IMPULSE ACCELERATED TECHNOLOGIES,
 INC. REDISTRIBUTABLE IP LICENSE AGREEMENT, and provided that this
 copyright statement is not removed from the file, and that any
 derivative work contains this copyright notice.

 Stage Master is Copyright 2002-2005, Green Mountain Computing Systems, Inc.
 All rights reserved.
********************************************************************************/

#include "co.h"

/* Architecture Includes */
#include <stdlib.h>
#include "arithmetic.h"


extern void *ext0_alloc(size_t);
extern void *alloc_shared(size_t);

/* Run Procedures */
extern void Producer(co_stream, FloatType* arg);
extern void fpga(co_stream, co_stream);
extern void Consumer(co_stream, FloatType* arg);

co_architecture co_initialize(FloatType* i, FloatType* o)
{
  co_stream input;
  co_stream output;

  unsigned int membase;

  input=co_stream_create("input",INT_TYPE(32),2);
  output=co_stream_create("output",INT_TYPE(32),2);
  co_process_create("Producer",(co_function)Producer,
                    2,
                    input,
                    i);
  co_process_create("Consumer",(co_function)Consumer,
                    2,
                    output,
                    o);

  /* Architecture Initialization */
  co_stream_attach(input,0,HW_INPUT);
  co_stream_attach(output,4,HW_OUTPUT);

  return(NULL);

}
