///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2006 Impulse Accelerated Technologies, Inc.
// 

#define STREAMDEPTH 100	/* buffer size for FIFO in hardware */
#define STREAMWIDTH 32	/* buffer width for FIFO in hardware */

#define INPUT_FILE "filter_in.dat"
#define OUTPUT_FILE "filter_out.dat"

#define CANT_DATOS_ESPERADOS      90
#define CANT_COORD_POR_ESTRUCTURA 15
//#define size_t co_uint32
