///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2007 Impulse Accelerated Technologies, Inc.
// 
// FPGA_sw.c: includes the software test bench processes and
// main() function.
//


#include <stdio.h>
#include "co.h"
#include "cosim_log.h"
#include "FPGA.h"
#include "arithmetic.h"
#include "types.h"


extern co_architecture co_initialize(FloatType* i, FloatType* o);

void Producer(co_stream input, FloatType* buffer)
{
    int i;

    co_stream_open(input, O_WRONLY, INT_TYPE(STREAMWIDTH));

    for (i = 0; i < CANT_DATOS_ESPERADOS; ++i)
    {
        co_int32 val = (co_int32)(buffer[i]);
        co_stream_write(input, &val, sizeof(co_int32));
    }

    co_stream_close(input);
}

void Consumer(co_stream output, FloatType* input)
{
    co_int32 in;

    co_stream_open(output, O_RDONLY, INT_TYPE(STREAMWIDTH));
 
    while (co_stream_read(output, &in, sizeof(co_int32)) == co_err_none)
    {
        *input = (FloatType)in;
    }

    co_stream_close(output);
}

int co_processor_call(FloatType* i, FloatType* o)
{
    co_architecture my_arch;

    my_arch = co_initialize(i, o);

    co_execute(my_arch);

    return(0);
}


