///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2007 Impulse Accelerated Technologies, Inc.
// 
// FPGA_sw.c: includes the software test bench processes and
// main() function.
//

#include <stdio.h>
#include "co.h"
#include "cosim_log.h"
#include "FPGA.h"
#include "arithmetic.h"
#include "types.h"

extern co_architecture co_initialize(void *);

void Producer(co_stream input)
{
	FloatType buffer[STREAMDEPTH];
    FloatType p;
    Coord3d* first;
    Coord3d* second;
    int i;

	IF_SIM(cosim_logwindow log = cosim_logwindow_create("Producer");)

    first = (Coord3d*)(&buffer[0]);
    first[0].x = float_to_current(-0.296000f);
    first[0].y = float_to_current(-0.697000f);
    first[0].z = float_to_current(-0.359000f);
    first[1].x = float_to_current(-0.299000f);
    first[1].y = float_to_current(-0.613000f);
    first[1].z = float_to_current(-0.240000f);
    first[2].x = float_to_current(-0.169000f);
    first[2].y = float_to_current(-0.534000f);
    first[2].z = float_to_current(-0.230000f);
    first[3].x = float_to_current(-0.182000f);
    first[3].y = float_to_current(-0.404000f);
    first[3].z = float_to_current(-0.208000f);
    first[4].x = float_to_current(-0.068000f);
    first[4].y = float_to_current(-0.314000f);
    first[4].z = float_to_current(-0.204000f);
    first[5].x = float_to_current(-0.095000f);
    first[5].y = float_to_current(-0.193000f);
    first[5].z = float_to_current(-0.117000f);
    first[6].x = float_to_current(0.011000f);
    first[6].y = float_to_current(-0.122000f);
    first[6].z = float_to_current(-0.079000f);
    first[7].x = float_to_current(0.000000f);
    first[7].y = float_to_current(0.000000f);
    first[7].z = float_to_current(0.000000f);
    first[8].x = float_to_current(0.102000f);
    first[8].y = float_to_current(0.101000f);
    first[8].z = float_to_current(-0.052000f);
    first[9].x = float_to_current(0.074000f);
    first[9].y = float_to_current(0.229000f);
    first[9].z = float_to_current(-0.028000f);
    first[10].x = float_to_current(0.165000f);
    first[10].y = float_to_current(0.335000f);
    first[10].z = float_to_current(-0.071000f);
    first[11].x = float_to_current(0.204000f);
    first[11].y = float_to_current(0.422000f);
    first[11].z = float_to_current(0.048000f);
    first[12].x = float_to_current(0.329000f);
    first[12].y = float_to_current(0.465000f);
    first[12].z = float_to_current(0.051000f);
    first[13].x = float_to_current(0.377000f);
    first[13].y = float_to_current(0.551000f);
    first[13].z = float_to_current(0.159000f);
    first[14].x = float_to_current(0.515000f);
    first[14].y = float_to_current(0.603000f);
    first[14].z = float_to_current(0.122000f);
    second = (Coord3d*)&(first[15].x);
    second[0].x = float_to_current(0.187000f);
    second[0].y = float_to_current(-0.528000f);
    second[0].z = float_to_current(-0.120000f);
    second[1].x = float_to_current(0.052000f);
    second[1].y = float_to_current(-0.561000f);
    second[1].z = float_to_current(-0.073000f);
    second[2].x = float_to_current(-0.044000f);
    second[2].y = float_to_current(-0.443000f);
    second[2].z = float_to_current(-0.083000f);
    second[3].x = float_to_current(-0.053000f);
    second[3].y = float_to_current(-0.379000f);
    second[3].z = float_to_current(-0.199000f);
    second[4].x = float_to_current(-0.146000f);
    second[4].y = float_to_current(-0.272000f);
    second[4].z = float_to_current(-0.226000f);
    second[5].x = float_to_current(-0.138000f);
    second[5].y = float_to_current(-0.152000f);
    second[5].z = float_to_current(-0.133000f);
    second[6].x = float_to_current(-0.019000f);
    second[6].y = float_to_current(-0.117000f);
    second[6].z = float_to_current(-0.085000f);
    second[7].x = float_to_current(0.000000f);
    second[7].y = float_to_current(0.000000f);
    second[7].z = float_to_current(0.000000f);
    second[8].x = float_to_current(0.135000f);
    second[8].y = float_to_current(0.064000f);
    second[8].z = float_to_current(-0.032000f);
    second[9].x = float_to_current(0.144000f);
    second[9].y = float_to_current(0.194000f);
    second[9].z = float_to_current(-0.007000f);
    second[10].x = float_to_current(0.267000f);
    second[10].y = float_to_current(0.268000f);
    second[10].z = float_to_current(-0.030000f);
    second[11].x = float_to_current(0.325000f);
    second[11].y = float_to_current(0.306000f);
    second[11].z = float_to_current(0.107000f);
    second[12].x = float_to_current(0.456000f);
    second[12].y = float_to_current(0.296000f);
    second[12].z = float_to_current(0.121000f);
    second[13].x = float_to_current(0.518000f);
    second[13].y = float_to_current(0.332000f);
    second[13].z = float_to_current(0.249000f);
    second[14].x = float_to_current(0.638000f);
    second[14].y = float_to_current(0.423000f);
    second[14].z = float_to_current(0.223000f);

	co_stream_open(input, O_WRONLY, INT_TYPE(STREAMWIDTH));
	IF_SIM(cosim_logwindow_write(log, "Sending test data...\n");)
    
    for (i = 0; i < CANT_DATOS_ESPERADOS; ++i)
    {
        FloatType out = buffer[i];
	    co_stream_write(input, &out, sizeof(FloatType));
    }

	IF_SIM(cosim_logwindow_write(log, "Finished writing test data.\n");)
	co_stream_close(input);
}

void Consumer(co_stream output)
{
    FloatType in;

	IF_SIM(cosim_logwindow log = cosim_logwindow_create("Consumer");)

	co_stream_open(output, O_RDONLY, INT_TYPE(STREAMWIDTH));
  
	IF_SIM(cosim_logwindow_write(log, "Consumer reading data...\n");)

	while (co_stream_read(output, &in, sizeof(FloatType)) == co_err_none)
    {
        printf("Consumer read %f from stream: output\n", current_to_float(in));
    }

	co_stream_close(output);
}

int main(int argc, char *argv[])
{
	co_architecture my_arch;
	void *param = NULL;
	int c;

	printf("Impulse C is Copyright(c) 2003-2007 Impulse Accelerated Technologies, Inc.\n");
  
	my_arch = co_initialize(param);
	co_execute(my_arch);

	printf("\n\nApplication complete. Press the Enter key to continue.\n");
	c = getc(stdin);

	return(0);
}


