///////////////////////////////////////////////////////////////////////////////
//
// Generated by Impulse CoDeveloper
// Impulse C is Copyright(c) 2003-2006 Impulse Accelerated Technologies, Inc.
// 

#define STREAMDEPTH 2	/* buffer size for FIFO in hardware */
#define STREAMWIDTH 32	/* buffer width for FIFO in hardware */

#define CANT_COORD_POR_ESTRUCTURA 15
