#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:G:\diseno_edk_ip_core_OPTIMIZADO\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = G:/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex4

DEVICE = xc4vfx12sf363-10

LANGUAGE = vhdl

SEARCHPATHOPT = 

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

PPC405_0_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_0.elf

BRAMINIT_ELF_FILES =   $(PPC405_0_BOOTLOOP) 
BRAMINIT_ELF_FILE_ARGS =   -pe ppc405_0  $(PPC405_0_BOOTLOOP) 

ALL_USER_ELF_FILES = 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM).do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM).do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM).do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti -X G:/diseno_edk_ip_core_OPTIMIZADO/ -E G:/diseno_edk_ip_core_OPTIMIZADO/


LIBRARIES =  \
       ppc405_0/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = ppc405_0_libsclean 

PROGRAMCLEAN_TARGETS = 

CORE_STATE_DEVELOPMENT_FILES = G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\divmod.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\gmem.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\fifo.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\fifo_dc.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\csignal.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\cregister.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\stream.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\stream_dc.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\impack.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\mem_if.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\impulse\hdl\vhdl\apu_if.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\apu_FPGA_arch_v1_00_a\hdl\vhdl\FPGA_ip.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\apu_FPGA_arch_v1_00_a\hdl\vhdl\FPGA_comp.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\apu_FPGA_arch_v1_00_a\hdl\vhdl\FPGA_top.vhd \
G:\diseno_edk_ip_core_OPTIMIZADO\pcores\apu_FPGA_arch_v1_00_a\hdl\vhdl\apu_FPGA_arch.vhd

WRAPPER_NGC_FILES = implementation/ppc405_0_wrapper.ngc \
implementation/jtagppc_0_wrapper.ngc \
implementation/reset_block_wrapper.ngc \
implementation/plb_wrapper.ngc \
implementation/opb_wrapper.ngc \
implementation/plb2opb_wrapper.ngc \
implementation/rs232_wrapper.ngc \
implementation/trimode_mac_gmii_wrapper.ngc \
implementation/hard_temac_0_wrapper.ngc \
implementation/ddr_sdram_32mx16_wrapper.ngc \
implementation/plb_bram_if_cntlr_1_wrapper.ngc \
implementation/plb_bram_if_cntlr_1_bram_wrapper.ngc \
implementation/opb_intc_0_wrapper.ngc \
implementation/sysclk_inv_wrapper.ngc \
implementation/clk90_inv_wrapper.ngc \
implementation/ddr_clk90_inv_wrapper.ngc \
implementation/dcm_0_wrapper.ngc \
implementation/dcm_1_wrapper.ngc \
implementation/fcb_v10_0_wrapper.ngc \
implementation/apu_fpga_arch_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(BITGEN_UT_FILE) $(XFLOW_DEPENDENCY)
